# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workbench\PyQt\GSP\AutoConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
   def setupUi(self, Dialog):
      Dialog.setObjectName("Dialog")
      Dialog.resize(412, 240)
      Dialog.setSizeGripEnabled(False)
      self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
      self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
      self.verticalLayout.setObjectName("verticalLayout")
      spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
      self.verticalLayout.addItem(spacerItem)
      self.tip = QtWidgets.QLabel(Dialog)
      font = QtGui.QFont()
      font.setFamily("Arial")
      self.tip.setFont(font)
      self.tip.setObjectName("tip")
      self.verticalLayout.addWidget(self.tip)
      self.comboBoxPort = QtWidgets.QComboBox(Dialog)
      font = QtGui.QFont()
      font.setFamily("Arial")
      self.comboBoxPort.setFont(font)
      self.comboBoxPort.setEditable(True)
      self.comboBoxPort.setObjectName("comboBoxPort")
      self.verticalLayout.addWidget(self.comboBoxPort)
      spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
      self.verticalLayout.addItem(spacerItem1)
      self.horizontalLayout = QtWidgets.QHBoxLayout()
      self.horizontalLayout.setObjectName("horizontalLayout")
      spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
      self.horizontalLayout.addItem(spacerItem2)
      self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
      font = QtGui.QFont()
      font.setFamily("Arial")
      self.pushButtonCancel.setFont(font)
      self.pushButtonCancel.setObjectName("pushButtonCancel")
      self.horizontalLayout.addWidget(self.pushButtonCancel)
      self.pushButtonOk = QtWidgets.QPushButton(Dialog)
      font = QtGui.QFont()
      font.setFamily("Arial")
      self.pushButtonOk.setFont(font)
      self.pushButtonOk.setObjectName("pushButtonOk")
      self.horizontalLayout.addWidget(self.pushButtonOk)
      self.verticalLayout.addLayout(self.horizontalLayout)
      self.verticalLayout.setStretch(0, 2)
      self.verticalLayout.setStretch(2, 2)
      self.verticalLayout.setStretch(3, 2)
      self.verticalLayout.setStretch(4, 1)

      self.retranslateUi(Dialog)
      QtCore.QMetaObject.connectSlotsByName(Dialog)

   def retranslateUi(self, Dialog):
      _translate = QtCore.QCoreApplication.translate
      Dialog.setWindowTitle(_translate("Dialog", "自动连接"))
      self.tip.setText(_translate("Dialog", "请选择连接端口"))
      self.pushButtonCancel.setText(_translate("Dialog", "取消"))
      self.pushButtonOk.setText(_translate("Dialog", "确定"))


if __name__ == "__main__":
   import sys
   app = QtWidgets.QApplication(sys.argv)
   Dialog = QtWidgets.QDialog()
   ui = Ui_Dialog()
   ui.setupUi(Dialog)
   Dialog.show()
   sys.exit(app.exec_())
