# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\workbench\PyQt\GSP\option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Option(object):
    def setupUi(self, Option):
        Option.setObjectName("Option")
        Option.resize(639, 489)
        self.verticalLayout = QtWidgets.QVBoxLayout(Option)
        self.verticalLayout.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Option)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fontLine = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.fontLine.setFont(font)
        self.fontLine.setReadOnly(True)
        self.fontLine.setObjectName("fontLine")
        self.horizontalLayout.addWidget(self.fontLine)
        self.fontButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.fontButton.setFont(font)
        self.fontButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.fontButton.setObjectName("fontButton")
        self.horizontalLayout.addWidget(self.fontButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.softInfo = QtWidgets.QTextBrowser(self.tab_2)
        self.softInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.softInfo.setObjectName("softInfo")
        self.verticalLayout_2.addWidget(self.softInfo)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Option)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Option)

    def retranslateUi(self, Option):
        _translate = QtCore.QCoreApplication.translate
        Option.setWindowTitle(_translate("Option", "选项"))
        self.fontButton.setText(_translate("Option", "字体"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Option", "显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Option", "关于"))
