# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\PyQt5\SerialPort\SerialPort.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 6, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 6, 2)
        self.groupBoxPort = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPort.sizePolicy().hasHeightForWidth())
        self.groupBoxPort.setSizePolicy(sizePolicy)
        self.groupBoxPort.setMinimumSize(QtCore.QSize(210, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.groupBoxPort.setFont(font)
        self.groupBoxPort.setObjectName("groupBoxPort")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxPort)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBoxPort = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.gridLayout_2.addWidget(self.comboBoxPort, 0, 1, 1, 1)
        self.comboBoxBaud = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxBaud.setObjectName("comboBoxBaud")
        self.gridLayout_2.addWidget(self.comboBoxBaud, 1, 1, 1, 1)
        self.comboBoxDataBit = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxDataBit.setObjectName("comboBoxDataBit")
        self.gridLayout_2.addWidget(self.comboBoxDataBit, 2, 1, 1, 1)
        self.comboBoxFlow = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxFlow.setObjectName("comboBoxFlow")
        self.gridLayout_2.addWidget(self.comboBoxFlow, 5, 1, 1, 1)
        self.comboBoxStopBit = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxStopBit.setObjectName("comboBoxStopBit")
        self.gridLayout_2.addWidget(self.comboBoxStopBit, 4, 1, 1, 1)
        self.comboBoxParity = QtWidgets.QComboBox(self.groupBoxPort)
        self.comboBoxParity.setObjectName("comboBoxParity")
        self.gridLayout_2.addWidget(self.comboBoxParity, 3, 1, 1, 1)
        self.labelPort = QtWidgets.QLabel(self.groupBoxPort)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout_2.addWidget(self.labelPort, 0, 0, 1, 1)
        self.labelBaud = QtWidgets.QLabel(self.groupBoxPort)
        self.labelBaud.setObjectName("labelBaud")
        self.gridLayout_2.addWidget(self.labelBaud, 1, 0, 1, 1)
        self.labelDataBit = QtWidgets.QLabel(self.groupBoxPort)
        self.labelDataBit.setObjectName("labelDataBit")
        self.gridLayout_2.addWidget(self.labelDataBit, 2, 0, 1, 1)
        self.labelParity = QtWidgets.QLabel(self.groupBoxPort)
        self.labelParity.setObjectName("labelParity")
        self.gridLayout_2.addWidget(self.labelParity, 3, 0, 1, 1)
        self.labelStopBit = QtWidgets.QLabel(self.groupBoxPort)
        self.labelStopBit.setObjectName("labelStopBit")
        self.gridLayout_2.addWidget(self.labelStopBit, 4, 0, 1, 1)
        self.labelFlow = QtWidgets.QLabel(self.groupBoxPort)
        self.labelFlow.setObjectName("labelFlow")
        self.gridLayout_2.addWidget(self.labelFlow, 5, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout.addWidget(self.groupBoxPort, 0, 0, 2, 1)
        self.groupBoxRecv = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxRecv.sizePolicy().hasHeightForWidth())
        self.groupBoxRecv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBoxRecv.setFont(font)
        self.groupBoxRecv.setObjectName("groupBoxRecv")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxRecv)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxEcho = QtWidgets.QCheckBox(self.groupBoxRecv)
        self.checkBoxEcho.setObjectName("checkBoxEcho")
        self.gridLayout_3.addWidget(self.checkBoxEcho, 2, 0, 1, 1)
        self.radioButtonRecvHex = QtWidgets.QRadioButton(self.groupBoxRecv)
        self.radioButtonRecvHex.setObjectName("radioButtonRecvHex")
        self.gridLayout_3.addWidget(self.radioButtonRecvHex, 0, 1, 1, 1)
        self.radioButtonRecvASCII = QtWidgets.QRadioButton(self.groupBoxRecv)
        self.radioButtonRecvASCII.setObjectName("radioButtonRecvASCII")
        self.gridLayout_3.addWidget(self.radioButtonRecvASCII, 0, 0, 1, 1)
        self.checkBoxTime = QtWidgets.QCheckBox(self.groupBoxRecv)
        self.checkBoxTime.setObjectName("checkBoxTime")
        self.gridLayout_3.addWidget(self.checkBoxTime, 3, 0, 1, 1)
        self.checkBoxNewLine = QtWidgets.QCheckBox(self.groupBoxRecv)
        self.checkBoxNewLine.setObjectName("checkBoxNewLine")
        self.gridLayout_3.addWidget(self.checkBoxNewLine, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxRecv, 2, 0, 1, 1)
        self.groupBoxSend = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSend.sizePolicy().hasHeightForWidth())
        self.groupBoxSend.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBoxSend.setFont(font)
        self.groupBoxSend.setObjectName("groupBoxSend")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxSend)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButtonSendASCII = QtWidgets.QRadioButton(self.groupBoxSend)
        self.radioButtonSendASCII.setObjectName("radioButtonSendASCII")
        self.gridLayout_4.addWidget(self.radioButtonSendASCII, 0, 0, 1, 1)
        self.radioButtonSendHex = QtWidgets.QRadioButton(self.groupBoxSend)
        self.radioButtonSendHex.setObjectName("radioButtonSendHex")
        self.gridLayout_4.addWidget(self.radioButtonSendHex, 0, 1, 1, 1)
        self.checkBoxRetry = QtWidgets.QCheckBox(self.groupBoxSend)
        self.checkBoxRetry.setObjectName("checkBoxRetry")
        self.gridLayout_4.addWidget(self.checkBoxRetry, 1, 0, 1, 1)
        self.spinBoxTime = QtWidgets.QSpinBox(self.groupBoxSend)
        self.spinBoxTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxTime.setMinimum(10)
        self.spinBoxTime.setMaximum(1000000000)
        self.spinBoxTime.setSingleStep(100)
        self.spinBoxTime.setProperty("value", 1000)
        self.spinBoxTime.setObjectName("spinBoxTime")
        self.gridLayout_4.addWidget(self.spinBoxTime, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxSend, 3, 0, 1, 1)
        self.pushButtonSend = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSend.sizePolicy().hasHeightForWidth())
        self.pushButtonSend.setSizePolicy(sizePolicy)
        self.pushButtonSend.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout.addWidget(self.pushButtonSend, 6, 2, 1, 1)
        self.comboBoxSend = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxSend.setObjectName("comboBoxSend")
        self.gridLayout.addWidget(self.comboBoxSend, 7, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.gridLayout.setRowStretch(5, 2)
        self.gridLayout.setRowStretch(6, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.run = QtWidgets.QAction(MainWindow)
        self.run.setCheckable(True)
        self.run.setObjectName("run")
        self.stop = QtWidgets.QAction(MainWindow)
        self.stop.setObjectName("stop")
        self.toolBar.addAction(self.run)
        self.toolBar.addAction(self.stop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxPort.setTitle(_translate("MainWindow", "串口设置"))
        self.labelPort.setText(_translate("MainWindow", "端    口"))
        self.labelBaud.setText(_translate("MainWindow", "波特率"))
        self.labelDataBit.setText(_translate("MainWindow", "数据位"))
        self.labelParity.setText(_translate("MainWindow", "校验位"))
        self.labelStopBit.setText(_translate("MainWindow", "停止位"))
        self.labelFlow.setText(_translate("MainWindow", "流    控"))
        self.groupBoxRecv.setTitle(_translate("MainWindow", "接收设置"))
        self.checkBoxEcho.setText(_translate("MainWindow", "显示发送"))
        self.radioButtonRecvHex.setText(_translate("MainWindow", "HEX"))
        self.radioButtonRecvASCII.setText(_translate("MainWindow", "ASCII"))
        self.checkBoxTime.setText(_translate("MainWindow", "显示时间"))
        self.checkBoxNewLine.setText(_translate("MainWindow", "自动换行"))
        self.groupBoxSend.setTitle(_translate("MainWindow", "发送设置"))
        self.radioButtonSendASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButtonSendHex.setText(_translate("MainWindow", "HEX"))
        self.checkBoxRetry.setText(_translate("MainWindow", "自动重发ms"))
        self.pushButtonSend.setText(_translate("MainWindow", "发送"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.run.setText(_translate("MainWindow", "运行"))
        self.stop.setText(_translate("MainWindow", "停止"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

